ALL:
    [
        'youth_pop_5to18',
        'commute_priv_vehicle',
        'med_hhincome',
        'avg_ann_daily_traffic',
        'fragment_index',
        'TotalPop', 
        'Men', 
        'Women', 
        'Hispanic', 
        'White', 
        'Black', 
        'Native', 
        'Asian', 
        'Citizen', 
        'Income', 
        'IncomeErr', 
        'IncomePerCap', 
        'IncomePerCapErr', 
        'Poverty', 
        'ChildPoverty', 
        'Professional', 
        'Service', 
        'Office', 
        'Construction', 
        'Production', 
        'Drive', 
        'Carpool', 
        'Transit', 
        'Walk', 
        'OtherTransp', 
        'WorkAtHome', 
        'MeanCommute', 
        'Employed', 
        'PrivateWork', 
        'PublicWork', 
        'SelfEmployed', 
        'FamilyWork', 
        'Unemployment'
    ]

NO_NANS:
    [
        'youth_pop_5to18',
        'commute_priv_vehicle',
        'med_hhincome',
        'avg_ann_daily_traffic',
        'fragment_index',
        'TotalPop', 
        'Men', 
        'Women', 
        'Hispanic', 
        'White', 
        'Black', 
        'Native', 
        'Asian', 
        'Citizen', 
        'IncomePerCap', 
        'IncomePerCapErr', 
        'Poverty', 
        'ChildPoverty', 
        'Professional', 
        'Service', 
        'Office', 
        'Construction', 
        'Production', 
        'Drive', 
        'Carpool', 
        'Transit', 
        'Walk', 
        'OtherTransp', 
        'WorkAtHome', 
        'Employed', 
        'PrivateWork', 
        'PublicWork', 
        'SelfEmployed', 
        'FamilyWork', 
        'Unemployment'
    ]
